# Hugo configuration

baseurl      = "https://blog.spatof.org/"
title        = "Daniel's blog"
languageCode = "en-us"
paginate     = "10" # Number of posts per page
theme        = "LoveIt"

[permalinks]
posts = '/posts/:year/:month/:title/'

[markup]
[markup.highlight]
# the LoveIt theme requires noClasses to be false
noClasses = false
style     = "rose-pine-dawn"
tabWidth  = 4

[Author] # Used in authorbox
name = "Daniel Kertesz"

[menu]
[[menu.main]]
weight     = 1
identifier = "posts"
name       = "Posts"
url        = "/posts/"

[[menu.main]]
weight     = 2
identifier = "tags"
name       = "Tags"
url        = "/tags/"

[[menu.main]]
weight     = 3
identifier = "categories"
name       = "Categories"
url        = "/categories/"

[params.header]
[params.header.title]
name = "blog.spatof.org"

[params.home]
[params.home.profile]
enable        = true
gravatarEmail = "daniel@spatof.org"
title         = "Daniel's blog"
subtitle      = "Thoughts and notes about computers and stuff."
typeit        = false
social        = true

[params.home.posts]
enable = true

[params.social]
GitHub   = "piger"
Mastodon = "https://mastodon.social/@piger"
email    = "daniel -at- spatof.org"
RSS      = true

[params.search]
enable = true
type   = "lunr"

[params.page]
[params.page.code]
copy = true
maxShownLines=500

[params.page.share]
enable     = true
twitter    = false
facebook   = false
hackernews = true
reddit     = true
line       = false
weibo      = false

[params.footer]
license = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.'
since   = 2013
custom  = "<script type='text/javascript' src='https://storage.ko-fi.com/cdn/widget/Widget_2.js'></script><script type='text/javascript'>kofiwidget2.init('Support Me on Ko-fi', '#29abe0', 'U6U07489O');kofiwidget2.draw();</script>"
